### PR TITLE
Add Q-learning and SARSA agents

### PR DESCRIPTION
**Pull request by riiswa**
## Description

This PR add 2 tabular agents: Q-Learning and SARSA (continuity of #254).

## TODO 

Add 1 example for qlearning and 1 for sarsa. (video plot)

### CODE REVIEW

**Comment by KohlerHECTOR** [comment]
Hello it looks good to me, do we usually use the typing library ?

**Comment by riiswa** [comment]
> Hello it looks good to me, do we usually use the typing library ?

Yes (see #293)

**Review by TimotheeMathieu — COMMENTED** [review]
Looks good to me. I did not check the code carefully but it seems ok. 
The docstrings are nice, maybe you can add a "attributes" section (with self.Q typically to say where to go search for Q function) and an examples section (those are optional for now in rlberry but it is nice to have them for QL and SARSA because these are basic algo). See [numpy docsting](https://numpydoc.readthedocs.io/en/latest/format.html#documenting-classes) for more info on how to style these sections.

Otherwise, you should also add the two agents in [api.rst](https://github.com/rlberry-py/rlberry/blob/main/docs/api.rst) for them to appear in the documentation, add the change to the changelog  in [changelog.rst](https://github.com/rlberry-py/rlberry/blob/main/docs/changelog.rst) and add the agents to the regular tests in [test_agent.py](https://github.com/rlberry-py/rlberry/blob/main/rlberry/tests/test_agent.py) and yes as you pointed out examples would be nice :)

Thanks!

**Comment by riiswa** [comment]
Done, sorry for the delay @TimotheeMathieu :)

**Pull request merged**
