### PR TITLE
Ppo ctn actions #262

### PR DESCRIPTION
**Pull request by KohlerHECTOR**
## Description
Updated model factory so that it builds a multivariate normal policy when action space is continuous. Updated PPO and A2C accordingly. Test on Pendulum-v1. 

Note: Covariance matrix is fixed to 2 * Identity(action_dimension)

### CODE REVIEW

**Comment by mmcenta** [comment]
Do you have experimental results?

**Comment by KohlerHECTOR** [comment]
> Do you have experimental results?

Nope I just did check for no run time errors on Pendulum :)

**Comment by KohlerHECTOR** [comment]
> > Do you have experimental results?
> 
> Nope I just did check for no run time errors on Pendulum :)

results 
[a2c_ppo_pendul_rewards.pdf](https://github.com/rlberry-py/rlberry/files/10267843/a2c_ppo_pendul_rewards.pdf)
[a2c_ppo_pendul_eval.pdf](https://github.com/rlberry-py/rlberry/files/10267844/a2c_ppo_pendul_eval.pdf)

**Comment by KohlerHECTOR** [comment]
Ok I give up.

**Review by TimotheeMathieu — APPROVED** [review]
LGTM Thanks.

**Pull request merged**
