### PR TITLE
Implemented a version of the LSVI-UCB algorithm by Jin et al. (2020)

### PR DESCRIPTION
**Pull request by omardrwch**
Paper: https://arxiv.org/pdf/1907.05388.pdf

### CODE REVIEW

**Comment by xuedong** [comment]
Please revise your code style.

**Comment by omardrwch** [comment]
Now it's a problem with codacy, not my code :D

**Comment by szrlee** [comment]
Hi,
Why LSVI-UCB is removed from the current version?
Is there a plan for algorithm with linear function approximation?

**Comment by omardrwch** [comment]
Hello,

We removed it from the 0.1 release because we wanted to test the implementation a little bit more. 
I tested it with some sort of RBF features in a GridWorld, and I just merged a new PR including it back (#53).

The script `examples/demo_lsvi_ucb.py` shows the experiment that I did with those features, and shows the comparison between LSVI-UCB, UCBVI, and the optimal policy: 

lsvi

Notice that LSVI-UCB is much slower than UCBVI, for instance, because it's runtime (per episode) increases with the number of episodes (plot `dw_time_elapsed`).

**Pull request merged**
